;; -*- coding: utf-8 -*-
(defun kleinmann-large-font ()
  (interactive)
  (set-frame-font "Source Code Pro for Powerline 24"))
(defun kleinmann-normal-font ()
  (interactive)
  (set-frame-font "Source Code Pro for Powerline 16"))
(defun kleinmann-small-font ()
  (interactive)
  (set-frame-font "Source Code Pro for Powerline 12"))
(defun kleinmann-switch-dictionary()
  (interactive)
  (let* ((dic ispell-current-dictionary)
         (change (if (string= dic "deutsch8") "english" "deutsch8")))
    (ispell-change-dictionary change)
    (message "Dictionary switched from %s to %s" dic change)
    ))
(defun kleinmann-ruby-open-spec-other-buffer ()
  (interactive)
  (when (featurep 'rspec-mode)
    (let ((source-buffer (current-buffer))
          (other-buffer (progn
                          (rspec-toggle-spec-and-target)
                          (current-buffer))))
      (switch-to-buffer source-buffer)
      (pop-to-buffer other-buffer))))
(defun kleinmann-build-ctags ()
  (interactive)
  (message "building project tags")
  (let ((default-directory (eproject-root)))
    (shell-command (concat "ctags -e -R --extra=+fq --exclude=db --exclude=.git --exclude=logs --exclude=public -f TAGS"))
    (message "tags built successfully")))
